---
framework: mocha
blacklist:
  - "test/watch.js"
coverageThreshold:
  branches: 80
  lines: 80
  functions: 80
  statements: 80
postMerge:
  pattern:
    - "./test/*.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  - "./test/*.js"
preRun:
  - npm i
postRun:
  - node --version
  - node --version
version: 2.0

######### abcd############
######### efg #############
